version: '3.8'

networks:
  local:

services:
  app:
    container_name: "${QUARKUS_APP_DOCKER_NAME-app}"
    image: serrodcal/quarkus-s3-reactive-routes:1.0.0
    networks:
      - local
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_S3_ENDPOINT=http://localstack:4566
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack:0.12.7
    networks:
      - local
    ports:
      - "4566:4566"
      #- "4571:4571"
      #- "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8081}"
    environment:
      - SERVICES=${SERVICES-s3}
      - START_WEB=0
      #- DEBUG=${DEBUG- }
      #- DATA_DIR=${DATA_DIR- }
      #- PORT_WEB_UI=${PORT_WEB_UI-8081}
      #- LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      #- KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      #- DOCKER_HOST=unix:///var/run/docker.sock
      #- HOST_TMP_FOLDER=${TMPDIR}
      - INIT_SCRIPTS_PATH=${INIT_SCRIPTS_PATH-/docker-entrypoint-initaws.d}
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      #- "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      #- "/var/run/docker.sock:/var/run/docker.sock"